// <auto-generated />
using System;
using GasFireMonitoringServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GasFireMonitoringServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GasFireMonitoringServer.Models.Entities.Alarm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlarmMessage")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RawMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("SensorTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AlarmMessage")
                        .HasDatabaseName("IX_Alarms_AlarmMessage");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("IX_Alarms_SiteId_Basic");

                    b.HasIndex("SiteName")
                        .HasDatabaseName("IX_Alarms_SiteName");

                    b.HasIndex("Timestamp")
                        .IsDescending()
                        .HasDatabaseName("IX_Alarms_Timestamp");

                    b.HasIndex("SensorTag", "Timestamp")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Alarms_SensorTag_Timestamp");

                    b.HasIndex("SiteId", "Timestamp")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Alarms_SiteId_Timestamp");

                    b.HasIndex("SiteId", "Timestamp", "Id")
                        .IsDescending(false, true, false)
                        .HasDatabaseName("IX_Alarms_SiteId_Timestamp_Id");

                    b.ToTable("alarms", (string)null);
                });

            modelBuilder.Entity("GasFireMonitoringServer.Models.Entities.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("channel_id");

                    b.Property<double>("CurrentValue")
                        .HasColumnType("double")
                        .HasColumnName("current_value");

                    b.Property<int>("DetectorType")
                        .HasColumnType("int")
                        .HasColumnName("detector_type");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_updated");

                    b.Property<double>("ProcessValue")
                        .HasColumnType("double")
                        .HasColumnName("process_value");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("raw_json");

                    b.Property<int>("SiteId")
                        .HasColumnType("int")
                        .HasColumnName("site_id");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("site_name");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("StatusText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("status_text");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tag_name");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("topic");

                    b.Property<string>("Units")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("units");

                    b.HasKey("Id");

                    b.HasIndex("LastUpdated")
                        .HasDatabaseName("IX_Sensors_LastUpdated");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("IX_Sensors_SiteId_Basic");

                    b.HasIndex("TagName")
                        .HasDatabaseName("IX_Sensors_TagName");

                    b.HasIndex("DetectorType", "SiteId")
                        .HasDatabaseName("IX_Sensors_DetectorType_SiteId");

                    b.HasIndex("SiteId", "ChannelId")
                        .HasDatabaseName("IX_Sensors_SiteId_ChannelId");

                    b.HasIndex("SiteId", "Status")
                        .HasDatabaseName("IX_Sensors_SiteId_Status");

                    b.HasIndex("Status", "SiteId", "ChannelId")
                        .HasDatabaseName("IX_Sensors_Status_SiteId_ChannelId");

                    b.ToTable("sensor_last_values", (string)null);
                });

            modelBuilder.Entity("GasFireMonitoringServer.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllowedCountiesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("[]")
                        .HasColumnName("allowed_counties");

                    b.Property<string>("AllowedSitesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("[]")
                        .HasColumnName("allowed_sites");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_login_attempts");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("locked_until");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PermissionsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("[]")
                        .HasColumnName("permissions");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_Users_CreatedAt");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Users_IsActive_Basic");

                    b.HasIndex("LastLoginAt")
                        .IsDescending()
                        .HasDatabaseName("IX_Users_LastLoginAt");

                    b.HasIndex("Role")
                        .HasDatabaseName("IX_Users_Role_Basic");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Username_Basic");

                    b.HasIndex("FailedLoginAttempts", "IsActive")
                        .HasDatabaseName("IX_Users_FailedLoginAttempts_IsActive");

                    b.HasIndex("IsActive", "Username")
                        .HasDatabaseName("IX_Users_IsActive_Username");

                    b.HasIndex("Username", "IsActive")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Username_IsActive");

                    b.HasIndex("Role", "IsActive", "Username")
                        .HasDatabaseName("IX_Users_Role_IsActive_Username");

                    b.ToTable("Users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
